server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  # Opsional: handle error page ke index.html juga
  error_page 404 /index.html;

  # Cache static files (opsional untuk performance)
  location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
    expires 6M;
    access_log off;
    add_header Cache-Control "public";
  }
}