pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}

rootProject.name = "Mahirku"

include ':app'

// Expo Modules Autolinking (jika menggunakan Expo)
apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute().text.trim()).getParentFile().toString() + "/scripts/autolinking.gradle"
useExpoModules()