services:
  frontend:
    image: layangdigital/mahirku-frontend:latest
    depends_on:
      - backend
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`mahirku.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    image: layangdigital/mahirku-backend:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mahirku
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=mahirku
      - DB_HOST=db
      - PORT=5000
      - JWT_SECRET=675ffe2d468fece7fa614e942b65c44611e63993de0789fe5249c9344cea833698d404b2b957c6fbe54fc88d3c46c52e957be30d98d822533045dde5df0452f5
      - XENDIT_API_KEY=xnd_production_lYDUN855uViCro9u25cRH9M3vSHgMQRzaTei2Y6RnV48cY0UbeC6tyD05nEN
      - XENDIT_PUBLIC_KEY=xnd_public_production_vf34AtLlXwlWJzrORt0uzkJOl4NVBx78HZ7L_MwKbmwaVMwa6lu8eha1AkGjbN0N
      - XENDIT_BASE_URL=https://api.xendit.co
      - XENDIT_CALLBACK_URL=https://mahirku.com/api/payment/callback
      - XENDIT_SUCCESS_REDIRECT_URL=https://mahirku.com/payment-success
      - XENDIT_FAILURE_REDIRECT_URL=https://mahirku.com/payment-failed
      - XENDIT_CALLBACK_TOKEN=yyI0FqtmZBd1yczzKHZ0dzF2bwfzabmq8cx2N03KwiqJHgox
      - RUN_MIGRATIONS=false
      - RUN_SEEDS=false
    depends_on:
      - db
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`mahirku.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mahirku
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dokploy-network

volumes:
  pgdata:
    name: mahirku_pgdata
    external: true

networks:
  dokploy-network:
    external: true
