import { Request, Response } from 'express';
import User from '../models/User';
import AffiliateCommission from '../models/AffiliateCommission';
import Role from '../models/Role';
import bcrypt from 'bcryptjs';
import { Op } from 'sequelize';
import { ROLE } from '../middlewares/roleMiddleware';

/**
 * @route   POST /api/mitra/members
 * @desc    Add a new member under the current Mitra
 * @access  Mitra only
 */
export const addMember = async (req: Request, res: Response): Promise<void> => {
  const {
    username,
    email,
    password,
    fullname,
    phoneNumber,
    address,
  } = req.body;

  // Get Mitra ID from authenticated user
  const mitraId = (req as any).user.userId;

  try {
    const existing = await User.findOne({ where: { email } });
    if (existing) {
      res.status(409).json({ message: 'Email already exists' });
      return;
    }

    // Find User Role ID
    const userRole = await Role.findOne({ where: { name: 'user' } });
    if (!userRole) {
      res.status(500).json({ message: 'User role not found' });
      return;
    }

    const hashedPassword = await bcrypt.hash(password, 10);

    const newUser = await User.create({
      username,
      email,
      password: hashedPassword,
      fullname,
      phoneNumber,
      address,
      roleId: userRole.id,
      parentId: mitraId,
      tokens: 0,
    });

    res.status(201).json({
      message: 'Member added successfully',
      member: {
        id: newUser.id,
        username: newUser.username,
        email: newUser.email,
        fullname: newUser.fullname,
      }
    });
  } catch (err) {
    console.error('Error adding member:', err);
    res.status(500).json({ error: 'Failed to add member' });
  }
};

/**
 * @route   GET /api/mitra/members
 * @desc    Get all members under the current Mitra
 * @access  Mitra only
 */
export const getMembers = async (req: Request, res: Response): Promise<void> => {
  const mitraId = (req as any).user.userId;
  const page = parseInt(req.query.page as string) || 1;
  const limit = parseInt(req.query.limit as string) || 10;
  const search = req.query.search as string || '';
  const offset = (page - 1) * limit;

  try {
    const whereClause: any = { parentId: mitraId };

    if (search) {
      whereClause[Op.or] = [
        { fullname: { [Op.iLike]: `%${search}%` } },
        { email: { [Op.iLike]: `%${search}%` } }
      ];
    }

    const { count, rows: members } = await User.findAndCountAll({
      where: whereClause,
      include: [{ model: Role, as: 'role' }],
      attributes: { exclude: ['password'] },
      limit,
      offset,
      order: [['createdAt', 'DESC']]
    });

    // Get commissions generated by each member for the Mitra
    const membersWithStats = await Promise.all(members.map(async (member) => {
      let totalCommission = 0;
      const roleName = (member as any).role?.name;

      if (roleName === 'affiliator') {
        // For Affiliators, show their total earnings (what they earned)
        totalCommission = await AffiliateCommission.sum('amount', {
          where: { referrerId: member.id }
        });
      } else {
        // For Users, show what they generated for the Mitra
        totalCommission = await AffiliateCommission.sum('amount', {
          where: { 
            referrerId: mitraId,
            referredUserId: member.id
          }
        });
      }
      
      return {
        ...member.toJSON(),
        totalCommissionGenerated: totalCommission || 0
      };
    }));

    res.status(200).json({
      data: membersWithStats,
      meta: {
        total: count,
        page,
        limit,
        totalPages: Math.ceil(count / limit)
      }
    });
  } catch (err) {
    console.error('Error fetching members:', err);
    res.status(500).json({ error: 'Failed to fetch members' });
  }
};

/**
 * @route   GET /api/mitra/dashboard
 * @desc    Get Mitra dashboard statistics
 * @access  Mitra only
 */
export const getDashboardStats = async (req: Request, res: Response): Promise<void> => {
  const mitraId = (req as any).user.userId;

  try {
    // 1. Total Members
    const totalMembers = await User.count({ where: { parentId: mitraId } });

    // 2. Total Affiliators (Members who have become affiliators)
    const affiliatorRole = await Role.findOne({ where: { name: 'affiliator' } });
    let totalAffiliators = 0;
    if (affiliatorRole) {
      totalAffiliators = await User.count({ 
        where: { 
          parentId: mitraId,
          roleId: affiliatorRole.id 
        } 
      });
    }

    // 3. Total Commission
    const totalCommission = await AffiliateCommission.sum('amount', {
      where: { referrerId: mitraId }
    });

    // 4. Recent Commissions
    const recentCommissions = await AffiliateCommission.findAll({
      where: { referrerId: mitraId },
      limit: 5,
      order: [['createdAt', 'DESC']],
      include: [
        { model: User, as: 'referredUser', attributes: ['fullname', 'email'] }
      ]
    });

    res.status(200).json({
      totalMembers,
      totalAffiliators,
      totalCommission: totalCommission || 0,
      recentCommissions
    });
  } catch (err) {
    console.error('Error fetching dashboard stats:', err);
    res.status(500).json({ error: 'Failed to fetch dashboard stats' });
  }
};

/**
 * @route   POST /api/mitra/members/:id/promote
 * @desc    Promote a member (under current Mitra) to Affiliator
 * @access  Mitra only
 */
export const promoteMemberToAffiliator = async (req: Request, res: Response): Promise<void> => {
  const mitraId = (req as any).user.userId;
  const { id } = req.params;

  try {
    const member = await User.findByPk(id, { include: [{ model: Role, as: 'role' }] });
    if (!member) {
      res.status(404).json({ message: 'Member not found' });
      return;
    }

    // Ensure the member belongs to this Mitra
    if (member.parentId !== mitraId) {
      res.status(403).json({ message: 'You can only promote your own members' });
      return;
    }

    // If already affiliator, skip
    const affiliatorRole = await Role.findOne({ where: { name: 'affiliator' } });
    if (!affiliatorRole) {
      res.status(500).json({ message: 'Affiliator role not found' });
      return;
    }

    if (member.roleId === affiliatorRole.id) {
      res.status(200).json({ message: 'Member is already an affiliator' });
      return;
    }

    // Promote: set roleId to affiliator, keep parentId = mitraId
    member.roleId = affiliatorRole.id;
    await member.save();

    res.status(200).json({
      message: 'Member promoted to affiliator successfully',
      member: {
        id: member.id,
        fullname: member.fullname,
        email: member.email,
        roleId: member.roleId,
        parentId: member.parentId,
      }
    });
  } catch (err) {
    console.error('Error promoting member:', err);
    res.status(500).json({ error: 'Failed to promote member' });
  }
};
