import { Request, Response } from 'express';
import User from '../models/User';
import AffiliateCommission from '../models/AffiliateCommission';
import Role from '../models/Role';
import bcrypt from 'bcryptjs';
import { Op } from 'sequelize';

/**
 * @route   POST /api/mitra/members
 * @desc    Add a new member under the current Mitra
 * @access  Mitra only
 */
export const addMember = async (req: Request, res: Response): Promise<void> => {
  const {
    username,
    email,
    password,
    fullname,
    phoneNumber,
    address,
  } = req.body;

  // Get Mitra ID from authenticated user
  const mitraId = (req as any).user.userId;

  try {
    const existing = await User.findOne({ where: { email } });
    if (existing) {
      res.status(409).json({ message: 'Email already exists' });
      return;
    }

    // Find User Role ID
    const userRole = await Role.findOne({ where: { name: 'user' } });
    if (!userRole) {
      res.status(500).json({ message: 'User role not found' });
      return;
    }

    const hashedPassword = await bcrypt.hash(password, 10);

    const newUser = await User.create({
      username,
      email,
      password: hashedPassword,
      fullname,
      phoneNumber,
      address,
      roleId: userRole.id,
      parentId: mitraId,
      tokens: 0,
    });

    res.status(201).json({
      message: 'Member added successfully',
      member: {
        id: newUser.id,
        username: newUser.username,
        email: newUser.email,
        fullname: newUser.fullname,
      }
    });
  } catch (err) {
    console.error('Error adding member:', err);
    res.status(500).json({ error: 'Failed to add member' });
  }
};

/**
 * @route   GET /api/mitra/members
 * @desc    Get all members under the current Mitra
 * @access  Mitra only
 */
export const getMembers = async (req: Request, res: Response): Promise<void> => {
  const mitraId = (req as any).user.userId;

  try {
    const members = await User.findAll({
      where: { parentId: mitraId },
      include: [{ model: Role, as: 'role' }],
      attributes: { exclude: ['password'] }
    });

    // Get commissions generated by each member for the Mitra
    const membersWithStats = await Promise.all(members.map(async (member) => {
      const totalCommission = await AffiliateCommission.sum('amount', {
        where: { 
          referrerId: mitraId,
          referredUserId: member.id
        }
      });
      
      return {
        ...member.toJSON(),
        totalCommissionGenerated: totalCommission || 0
      };
    }));

    res.status(200).json(membersWithStats);
  } catch (err) {
    console.error('Error fetching members:', err);
    res.status(500).json({ error: 'Failed to fetch members' });
  }
};

/**
 * @route   GET /api/mitra/dashboard
 * @desc    Get Mitra dashboard statistics
 * @access  Mitra only
 */
export const getDashboardStats = async (req: Request, res: Response): Promise<void> => {
  const mitraId = (req as any).user.userId;

  try {
    // 1. Total Members
    const totalMembers = await User.count({ where: { parentId: mitraId } });

    // 2. Total Affiliators (Members who have become affiliators)
    const affiliatorRole = await Role.findOne({ where: { name: 'affiliator' } });
    let totalAffiliators = 0;
    if (affiliatorRole) {
      totalAffiliators = await User.count({ 
        where: { 
          parentId: mitraId,
          roleId: affiliatorRole.id 
        } 
      });
    }

    // 3. Total Commission
    const totalCommission = await AffiliateCommission.sum('amount', {
      where: { referrerId: mitraId }
    });

    // 4. Recent Commissions
    const recentCommissions = await AffiliateCommission.findAll({
      where: { referrerId: mitraId },
      limit: 5,
      order: [['createdAt', 'DESC']],
      include: [
        { model: User, as: 'referredUser', attributes: ['fullname', 'email'] }
      ]
    });

    res.status(200).json({
      totalMembers,
      totalAffiliators,
      totalCommission: totalCommission || 0,
      recentCommissions
    });
  } catch (err) {
    console.error('Error fetching dashboard stats:', err);
    res.status(500).json({ error: 'Failed to fetch dashboard stats' });
  }
};
