name: Build Docker images

on:
  push:
    branches: ["development"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/bake-action@v5
        with:
          files: |
            docker-compose.yml
            docker-compose.prod.yml
          push: true
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Deploy Frontend to Dokploy
        if: success()
        run: |
          curl -X 'POST' \
            'https://${{ secrets.DOKPLOY_DOMAIN }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{ "json":{ "applicationId": "${{ secrets.DOKPLOY_FRONTEND_ID }}" } }'

      - name: Deploy Backend to Dokploy
        if: success()
        run: |
          curl -X 'POST' \
            'https://${{ secrets.DOKPLOY_DOMAIN }}/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{ "json":{ "applicationId": "${{ secrets.DOKPLOY_BACKEND_ID }}" } }'